# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=dbg-c11_x86
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),dbg-c11_x86)
  partest_config = dbg-c11_x86

else ifeq ($(config),dbg-c11_x64)
  partest_config = dbg-c11_x64

else ifeq ($(config),dbg-c14_x86)
  partest_config = dbg-c14_x86

else ifeq ($(config),dbg-c14_x64)
  partest_config = dbg-c14_x64

else ifeq ($(config),dbg-c17_x86)
  partest_config = dbg-c17_x86

else ifeq ($(config),dbg-c17_x64)
  partest_config = dbg-c17_x64

else ifeq ($(config),dbg-c20_x86)
  partest_config = dbg-c20_x86

else ifeq ($(config),dbg-c20_x64)
  partest_config = dbg-c20_x64

else ifeq ($(config),rel-c11_x86)
  partest_config = rel-c11_x86

else ifeq ($(config),rel-c11_x64)
  partest_config = rel-c11_x64

else ifeq ($(config),rel-c14_x86)
  partest_config = rel-c14_x86

else ifeq ($(config),rel-c14_x64)
  partest_config = rel-c14_x64

else ifeq ($(config),rel-c17_x86)
  partest_config = rel-c17_x86

else ifeq ($(config),rel-c17_x64)
  partest_config = rel-c17_x64

else ifeq ($(config),rel-c20_x86)
  partest_config = rel-c20_x86

else ifeq ($(config),rel-c20_x64)
  partest_config = rel-c20_x64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := partest

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

partest:
ifneq (,$(partest_config))
	@echo "==== Building partest ($(partest_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(partest_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  dbg-c11_x86"
	@echo "  dbg-c11_x64"
	@echo "  dbg-c14_x86"
	@echo "  dbg-c14_x64"
	@echo "  dbg-c17_x86"
	@echo "  dbg-c17_x64"
	@echo "  dbg-c20_x86"
	@echo "  dbg-c20_x64"
	@echo "  rel-c11_x86"
	@echo "  rel-c11_x64"
	@echo "  rel-c14_x86"
	@echo "  rel-c14_x64"
	@echo "  rel-c17_x86"
	@echo "  rel-c17_x64"
	@echo "  rel-c20_x86"
	@echo "  rel-c20_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   partest"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"