name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-gcc:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            compiler: g++-11
            configs: [dbg-c11_x64, dbg-c14_x64, dbg-c17_x64]
            binpaths: [dbg-c11, dbg-c14, dbg-c17]
            
          - os: ubuntu-24.04
            compiler: g++-12
            configs: [dbg-c11_x64, dbg-c14_x64, dbg-c17_x64]
            binpaths: [dbg-c11, dbg-c14, dbg-c17]
            
          - os: ubuntu-24.04
            compiler: g++-13
            configs: [dbg-c11_x64, dbg-c14_x64, dbg-c17_x64, dbg-c20_x64]
            binpaths: [dbg-c11, dbg-c14, dbg-c17, dbg-c20]
            
          - os: ubuntu-24.04
            compiler: g++-14
            configs: [dbg-c11_x64, dbg-c14_x64, dbg-c17_x64, dbg-c20_x64]
            binpaths: [dbg-c11, dbg-c14, dbg-c17, dbg-c20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Premake and Generate Project Files
        run: |
          curl -L -o premake.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
          tar -xzf premake.tar.gz
          sudo mv premake5 /usr/local/bin/
          premake5 --version
          premake5 --os=linux gmake2

      - name: Install GCC
        run: sudo apt-get install -y ${{ matrix.compiler }}

      - name: Build GCC
        run: |
          for config in ${{ join(matrix.configs, ' ') }}; do
            make config=$config CXX=${{ matrix.compiler }}
          done
          
      - name: Run GCC
        run: |
          for binpath in ${{ join(matrix.binpaths, ' ') }}; do
            # Executable location is tied to Premake configuration
            bin/x64/${binpath}/partest
          done

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always() # && hashFiles('testResults.xml') != '' # Uncomment to only run if the JUnit file is present
        with:
          name: Partest Results
          path: testResults.xml
          reporter: java-junit
          # fail-on-empty: false      # ← don’t fail if the file doesn’t exist
            
  build-clang:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            package: clang-11
            compiler: clang++-11
            configs: [dbg-c11_x64, dbg-c14_x64, dbg-c17_x64]
            binpaths: [dbg-c11, dbg-c14, dbg-c17]

          - os: ubuntu-22.04
            package: clang-12
            compiler: clang++-12
            configs: [dbg-c11_x64, dbg-c14_x64, dbg-c17_x64]
            binpaths: [dbg-c11, dbg-c14, dbg-c17]

          - os: ubuntu-24.04
            package: clang-18
            compiler: clang++-18  
            configs: [dbg-c11_x64, dbg-c14_x64, dbg-c17_x64, dbg-c20_x64]
            binpaths: [dbg-c11, dbg-c14, dbg-c17, dbg-c20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Premake and Generate Project Files
        run: |
          curl -L -o premake.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
          tar -xzf premake.tar.gz
          sudo mv premake5 /usr/local/bin/
          premake5 --version
          premake5 --os=linux gmake2

      - name: Install Clang
        run: |
          sudo apt-get install ${{ matrix.package }} -y

      - name: Build Clang
        run: |
          for config in ${{ join(matrix.configs, ' ') }}; do
            make config=$config CXX=${{ matrix.compiler }}
          done
          
      - name: Run Clang
        run: |
          for binpath in ${{ join(matrix.binpaths, ' ') }}; do
            # Executable location is tied to Premake configuration
            bin/x64/${binpath}/partest
          done

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always() # && hashFiles('testResults.xml') != '' # Uncomment to only run if the JUnit file is present
        with:
          name: Partest Results
          path: testResults.xml
          reporter: java-junit
          # fail-on-empty: false      # ← don’t fail if the file doesn’t exist

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Premake and Generate Project Files
        run: |
          Invoke-WebRequest -Uri "https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip" -OutFile premake.zip
          Expand-Archive premake.zip -DestinationPath .
          # premake5.exe is now in the current directory
          .\premake5.exe vs2022

      - name: Set Up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build MSVC Debug
        run: |
          msbuild build\partest.vcxproj /p:Configuration=dbg-c14 /p:Platform=Win32
          msbuild build\partest.vcxproj /p:Configuration=dbg-c14 /p:Platform=x64
          msbuild build\partest.vcxproj /p:Configuration=dbg-c17 /p:Platform=Win32
          msbuild build\partest.vcxproj /p:Configuration=dbg-c17 /p:Platform=x64
          msbuild build\partest.vcxproj /p:Configuration=dbg-c20 /p:Platform=Win32
          msbuild build\partest.vcxproj /p:Configuration=dbg-c20 /p:Platform=x64
          
      - name: Run MSVC
        run: |
          bin\x86\dbg-c14\partest.exe
          bin\x64\dbg-c14\partest.exe
          bin\x86\dbg-c17\partest.exe
          bin\x64\dbg-c17\partest.exe
          bin\x86\dbg-c20\partest.exe
          bin\x64\dbg-c20\partest.exe

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always() # && hashFiles('testResults.xml') != '' # Uncomment to only run if the JUnit file is present
        with:
          name: Partest Results
          path: testResults.xml
          reporter: java-junit
          # fail-on-empty: false      # ← don’t fail if the file doesn’t exist